/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type PrimaryCta = {
  label?: string
  href?: string
}

export type SecondaryCta = {
  label?: string
  href?: string
}

export type SectionCtaPrimaryCta = {
  label?: string
  href?: string
}

export type SectionCtaSecondaryCta = {
  label?: string
  href?: string
}

export type SectionContact = {
  _type: 'sectionContact'
  heading?: string
  subheading?: string
}

export type SectionCta = {
  _type: 'sectionCta'
  heading?: string
  subheading?: string
  primaryCta?: SectionCtaPrimaryCta
  secondaryCta?: SectionCtaSecondaryCta
  variant?: 'brand' | 'dark' | 'light'
}

export type SectionBlogPreview = {
  _type: 'sectionBlogPreview'
  heading?: string
  count?: number
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type SectionGallery = {
  _type: 'sectionGallery'
  heading?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type SectionStats = {
  _type: 'sectionStats'
  heading?: string
  items?: Array<{
    value?: string
    label?: string
    _type: 'statItem'
    _key: string
  }>
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type SectionTestimonials = {
  _type: 'sectionTestimonials'
  heading?: string
  testimonials?: Array<
    {
      _key: string
    } & TestimonialReference
  >
}

export type SectionPricing = {
  _type: 'sectionPricing'
  heading?: string
  subheading?: string
  items?: Array<{
    name?: string
    description?: string
    price?: string
    duration?: string
    _type: 'pricingItem'
    _key: string
  }>
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type SectionServices = {
  _type: 'sectionServices'
  heading?: string
  subheading?: string
  services?: Array<
    {
      _key: string
    } & ServiceReference
  >
}

export type SectionTextImage = {
  _type: 'sectionTextImage'
  heading?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imagePosition?: 'left' | 'right'
}

export type SectionHero = {
  _type: 'sectionHero'
  heading?: string
  subheading?: string
  primaryCta?: PrimaryCta
  secondaryCta?: SecondaryCta
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type NavLink = {
  _type: 'navLink'
  label?: string
  href?: string
  openInNewTab?: boolean
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AuthorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'author'
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  excerpt?: string
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
  >
  author?: AuthorReference
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  publishedAt?: string
  featured?: boolean
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  bio?: string
  photo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  social?: {
    instagram?: string
    facebook?: string
    website?: string
  }
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  authorName?: string
  position?: string
  company?: string
  content?: string
  rating?: number
  photo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  publishedAt?: string
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  icon?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  pageBuilder?: Array<
    | ({
        _key: string
      } & SectionHero)
    | ({
        _key: string
      } & SectionTextImage)
    | ({
        _key: string
      } & SectionServices)
    | ({
        _key: string
      } & SectionPricing)
    | ({
        _key: string
      } & SectionTestimonials)
    | ({
        _key: string
      } & SectionStats)
    | ({
        _key: string
      } & SectionGallery)
    | ({
        _key: string
      } & SectionBlogPreview)
    | ({
        _key: string
      } & SectionCta)
    | ({
        _key: string
      } & SectionContact)
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  businessName?: string
  tagline?: string
  logoLight?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  logoDark?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  email?: string
  phone?: string
  address?: string
  googleMapsUrl?: string
  social?: {
    facebook?: string
    instagram?: string
    tiktok?: string
  }
  navLinks?: Array<
    {
      _key: string
    } & NavLink
  >
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PrimaryCta
  | SecondaryCta
  | SectionCtaPrimaryCta
  | SectionCtaSecondaryCta
  | SectionContact
  | SectionCta
  | SectionBlogPreview
  | SanityImageAssetReference
  | SectionGallery
  | SectionStats
  | TestimonialReference
  | SectionTestimonials
  | SectionPricing
  | ServiceReference
  | SectionServices
  | SectionTextImage
  | SectionHero
  | NavLink
  | Category
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Testimonial
  | Service
  | Page
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    businessName,    tagline,    logoLight { alt, asset-> { _id, url, metadata { dimensions } } },    logoDark { alt, asset-> { _id, url, metadata { dimensions } } },    email,    phone,    address,    googleMapsUrl,    social {      facebook,      instagram,      tiktok    },    "navLinks": navLinks[] {      label,      href,      openInNewTab    },    seo {      metaTitle,      metaDescription,      ogImage { ..., asset-> }    }  }
export type SiteSettingsQueryResult = {
  businessName: string | null
  tagline: string | null
  logoLight: {
    alt: string | null
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
      } | null
    } | null
  } | null
  logoDark: {
    alt: string | null
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
      } | null
    } | null
  } | null
  email: string | null
  phone: string | null
  address: string | null
  googleMapsUrl: string | null
  social: {
    facebook: string | null
    instagram: string | null
    tiktok: string | null
  } | null
  navLinks: Array<{
    label: string | null
    href: string | null
    openInNewTab: boolean | null
  }> | null
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    ogImage: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Source: sanity/queries.ts
// Variable: footerQuery
// Query: *[_type == "siteSettings"][0] {    businessName,    tagline,    logoLight { alt, asset-> { _id, url, metadata { dimensions } } },    logoDark { alt, asset-> { _id, url, metadata { dimensions } } },    email,    phone,    address,    googleMapsUrl,    social {      facebook,      instagram,      tiktok    }  }
export type FooterQueryResult = {
  businessName: string | null
  tagline: string | null
  logoLight: {
    alt: string | null
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
      } | null
    } | null
  } | null
  logoDark: {
    alt: string | null
    asset: {
      _id: string
      url: string | null
      metadata: {
        dimensions: SanityImageDimensions | null
      } | null
    } | null
  } | null
  email: string | null
  phone: string | null
  address: string | null
  googleMapsUrl: string | null
  social: {
    facebook: string | null
    instagram: string | null
    tiktok: string | null
  } | null
} | null

// Source: sanity/queries.ts
// Variable: allServicesQuery
// Query: *[_type == "service"] | order(_createdAt asc) {    _id,    title,    slug,    description,    icon,    image { ..., asset-> }  }
export type AllServicesQueryResult = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  icon: string | null
  image: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
}>

// Source: sanity/queries.ts
// Variable: allTestimonialsQuery
// Query: *[_type == "testimonial"] | order(_createdAt asc) {    _id,    authorName,    position,    company,    content,    rating,    photo { ..., asset-> },    publishedAt  }
export type AllTestimonialsQueryResult = Array<{
  _id: string
  authorName: string | null
  position: string | null
  company: string | null
  content: string | null
  rating: number | null
  photo: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  publishedAt: string | null
}>

// Source: sanity/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post"] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    mainImage { ..., asset-> },    "author": author-> {      name,      photo { ..., asset-> }    },    "categories": categories[]-> { title, slug },    publishedAt  }
export type AllPostsQueryResult = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  mainImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  author: {
    name: string | null
    photo: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  categories: Array<{
    title: string | null
    slug: Slug | null
  }> | null
  publishedAt: string | null
}>

// Source: sanity/queries.ts
// Variable: featuredPostsQuery
// Query: *[_type == "post" && featured == true] | order(publishedAt desc) [0...3] {    _id,    title,    slug,    excerpt,    mainImage { ..., asset-> },    "author": author-> {      name,      photo { ..., asset-> }    },    "categories": categories[]-> { title, slug },    publishedAt  }
export type FeaturedPostsQueryResult = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  mainImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  author: {
    name: string | null
    photo: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  categories: Array<{
    title: string | null
    slug: Slug | null
  }> | null
  publishedAt: string | null
}>

// Source: sanity/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    excerpt,    mainImage { ..., asset-> },    body,    "author": author-> {      name,      slug,      bio,      photo { ..., asset-> },      social    },    "categories": categories[]-> { title, slug },    publishedAt,    featured,    seo {      metaTitle,      metaDescription,      ogImage { ..., asset-> }    }  }
export type PostBySlugQueryResult = {
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  mainImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
  > | null
  author: {
    name: string | null
    slug: Slug | null
    bio: string | null
    photo: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
    social: {
      instagram?: string
      facebook?: string
      website?: string
    } | null
  } | null
  categories: Array<{
    title: string | null
    slug: Slug | null
  }> | null
  publishedAt: string | null
  featured: boolean | null
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    ogImage: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Source: sanity/queries.ts
// Variable: allPostsSlugsQuery
// Query: *[_type == "post"] { "slug": slug.current }
export type AllPostsSlugsQueryResult = Array<{
  slug: string | null
}>

// Source: sanity/queries.ts
// Variable: postsByCategoryQuery
// Query: *[_type == "post" && $categorySlug in categories[]->slug.current] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    mainImage { ..., asset-> },    "author": author-> {      name,      photo { ..., asset-> }    },    "categories": categories[]-> { title, slug },    publishedAt  }
export type PostsByCategoryQueryResult = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  mainImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  author: {
    name: string | null
    photo: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  categories: Array<{
    title: string | null
    slug: Slug | null
  }> | null
  publishedAt: string | null
}>

// Source: sanity/queries.ts
// Variable: allCategoriesQuery
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    slug,    description  }
export type AllCategoriesQueryResult = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
}>

// Source: sanity/queries.ts
// Variable: latestPostsQuery
// Query: *[_type == "post"] | order(publishedAt desc) [0...$limit] {    _id,    title,    slug,    excerpt,    mainImage { ..., asset-> },    publishedAt,    "author": author-> { name },    "categories": categories[]-> { title, slug }  }
export type LatestPostsQueryResult = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  excerpt: string | null
  mainImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  publishedAt: string | null
  author: {
    name: string | null
  } | null
  categories: Array<{
    title: string | null
    slug: Slug | null
  }> | null
}>

// Source: sanity/queries.ts
// Variable: allPagesSlugsQuery
// Query: *[_type == "page" && defined(slug.current) && slug.current != "home"] {    "slug": slug.current  }
export type AllPagesSlugsQueryResult = Array<{
  slug: string | null
}>

// Source: sanity/queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    seo,    pageBuilder[] {      _type,      _key,      _type == "sectionHero" => {        heading,        subheading,        primaryCta,        secondaryCta,        backgroundImage { ..., asset-> }      },      _type == "sectionTextImage" => {        heading,        body,        image { ..., asset-> },        imagePosition      },      _type == "sectionServices" => {        heading,        subheading,        services[]-> {          _id, title, description, icon,          image { ..., asset-> }        }      },      _type == "sectionPricing" => {        heading,        subheading,        items      },      _type == "sectionTestimonials" => {        heading,        testimonials[]-> {          _id, authorName, position, company, content, rating,          photo { ..., asset-> }        }      },      _type == "sectionStats" => {        heading,        items      },      _type == "sectionGallery" => {        heading,        images[] { ..., asset-> }      },      _type == "sectionBlogPreview" => {        heading,        count      },      _type == "sectionCta" => {        heading,        subheading,        primaryCta,        secondaryCta,        variant      },      _type == "sectionContact" => {        heading,        subheading      }    }  }
export type PageQueryResult = {
  _id: string
  title: string | null
  slug: Slug | null
  seo: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  } | null
  pageBuilder: Array<
    | {
        _type: 'sectionBlogPreview'
        _key: string
        heading: string | null
        count: number | null
      }
    | {
        _type: 'sectionContact'
        _key: string
        heading: string | null
        subheading: string | null
      }
    | {
        _type: 'sectionCta'
        _key: string
        heading: string | null
        subheading: string | null
        primaryCta: SectionCtaPrimaryCta | null
        secondaryCta: SectionCtaSecondaryCta | null
        variant: 'brand' | 'dark' | 'light' | null
      }
    | {
        _type: 'sectionGallery'
        _key: string
        heading: string | null
        images: Array<{
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
          _key: string
        }> | null
      }
    | {
        _type: 'sectionHero'
        _key: string
        heading: string | null
        subheading: string | null
        primaryCta: PrimaryCta | null
        secondaryCta: SecondaryCta | null
        backgroundImage: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        } | null
      }
    | {
        _type: 'sectionPricing'
        _key: string
        heading: string | null
        subheading: string | null
        items: Array<{
          name?: string
          description?: string
          price?: string
          duration?: string
          _type: 'pricingItem'
          _key: string
        }> | null
      }
    | {
        _type: 'sectionServices'
        _key: string
        heading: string | null
        subheading: string | null
        services: Array<{
          _id: string
          title: string | null
          description: string | null
          icon: string | null
          image: {
            asset: {
              _id: string
              _type: 'sanity.imageAsset'
              _createdAt: string
              _updatedAt: string
              _rev: string
              originalFilename?: string
              label?: string
              title?: string
              description?: string
              altText?: string
              sha1hash?: string
              extension?: string
              mimeType?: string
              size?: number
              assetId?: string
              uploadId?: string
              path?: string
              url?: string
              metadata?: SanityImageMetadata
              source?: SanityAssetSourceData
            } | null
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            alt?: string
            _type: 'image'
          } | null
        }> | null
      }
    | {
        _type: 'sectionStats'
        _key: string
        heading: string | null
        items: Array<{
          value?: string
          label?: string
          _type: 'statItem'
          _key: string
        }> | null
      }
    | {
        _type: 'sectionTestimonials'
        _key: string
        heading: string | null
        testimonials: Array<{
          _id: string
          authorName: string | null
          position: string | null
          company: string | null
          content: string | null
          rating: number | null
          photo: {
            asset: {
              _id: string
              _type: 'sanity.imageAsset'
              _createdAt: string
              _updatedAt: string
              _rev: string
              originalFilename?: string
              label?: string
              title?: string
              description?: string
              altText?: string
              sha1hash?: string
              extension?: string
              mimeType?: string
              size?: number
              assetId?: string
              uploadId?: string
              path?: string
              url?: string
              metadata?: SanityImageMetadata
              source?: SanityAssetSourceData
            } | null
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            alt?: string
            _type: 'image'
          } | null
        }> | null
      }
    | {
        _type: 'sectionTextImage'
        _key: string
        heading: string | null
        body: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }> | null
        image: {
          asset: {
            _id: string
            _type: 'sanity.imageAsset'
            _createdAt: string
            _updatedAt: string
            _rev: string
            originalFilename?: string
            label?: string
            title?: string
            description?: string
            altText?: string
            sha1hash?: string
            extension?: string
            mimeType?: string
            size?: number
            assetId?: string
            uploadId?: string
            path?: string
            url?: string
            metadata?: SanityImageMetadata
            source?: SanityAssetSourceData
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          alt?: string
          _type: 'image'
        } | null
        imagePosition: 'left' | 'right' | null
      }
  > | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    businessName,\n    tagline,\n    logoLight { alt, asset-> { _id, url, metadata { dimensions } } },\n    logoDark { alt, asset-> { _id, url, metadata { dimensions } } },\n    email,\n    phone,\n    address,\n    googleMapsUrl,\n    social {\n      facebook,\n      instagram,\n      tiktok\n    },\n    "navLinks": navLinks[] {\n      label,\n      href,\n      openInNewTab\n    },\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage { ..., asset-> }\n    }\n  }\n': SiteSettingsQueryResult
    '\n  *[_type == "siteSettings"][0] {\n    businessName,\n    tagline,\n    logoLight { alt, asset-> { _id, url, metadata { dimensions } } },\n    logoDark { alt, asset-> { _id, url, metadata { dimensions } } },\n    email,\n    phone,\n    address,\n    googleMapsUrl,\n    social {\n      facebook,\n      instagram,\n      tiktok\n    }\n  }\n': FooterQueryResult
    '\n  *[_type == "service"] | order(_createdAt asc) {\n    _id,\n    title,\n    slug,\n    description,\n    icon,\n    image { ..., asset-> }\n  }\n': AllServicesQueryResult
    '\n  *[_type == "testimonial"] | order(_createdAt asc) {\n    _id,\n    authorName,\n    position,\n    company,\n    content,\n    rating,\n    photo { ..., asset-> },\n    publishedAt\n  }\n': AllTestimonialsQueryResult
    '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage { ..., asset-> },\n    "author": author-> {\n      name,\n      photo { ..., asset-> }\n    },\n    "categories": categories[]-> { title, slug },\n    publishedAt\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && featured == true] | order(publishedAt desc) [0...3] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage { ..., asset-> },\n    "author": author-> {\n      name,\n      photo { ..., asset-> }\n    },\n    "categories": categories[]-> { title, slug },\n    publishedAt\n  }\n': FeaturedPostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage { ..., asset-> },\n    body,\n    "author": author-> {\n      name,\n      slug,\n      bio,\n      photo { ..., asset-> },\n      social\n    },\n    "categories": categories[]-> { title, slug },\n    publishedAt,\n    featured,\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage { ..., asset-> }\n    }\n  }\n': PostBySlugQueryResult
    '\n  *[_type == "post"] { "slug": slug.current }\n': AllPostsSlugsQueryResult
    '\n  *[_type == "post" && $categorySlug in categories[]->slug.current] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage { ..., asset-> },\n    "author": author-> {\n      name,\n      photo { ..., asset-> }\n    },\n    "categories": categories[]-> { title, slug },\n    publishedAt\n  }\n': PostsByCategoryQueryResult
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description\n  }\n': AllCategoriesQueryResult
    '\n  *[_type == "post"] | order(publishedAt desc) [0...$limit] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage { ..., asset-> },\n    publishedAt,\n    "author": author-> { name },\n    "categories": categories[]-> { title, slug }\n  }\n': LatestPostsQueryResult
    '\n  *[_type == "page" && defined(slug.current) && slug.current != "home"] {\n    "slug": slug.current\n  }\n': AllPagesSlugsQueryResult
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    seo,\n    pageBuilder[] {\n      _type,\n      _key,\n      _type == "sectionHero" => {\n        heading,\n        subheading,\n        primaryCta,\n        secondaryCta,\n        backgroundImage { ..., asset-> }\n      },\n      _type == "sectionTextImage" => {\n        heading,\n        body,\n        image { ..., asset-> },\n        imagePosition\n      },\n      _type == "sectionServices" => {\n        heading,\n        subheading,\n        services[]-> {\n          _id, title, description, icon,\n          image { ..., asset-> }\n        }\n      },\n      _type == "sectionPricing" => {\n        heading,\n        subheading,\n        items\n      },\n      _type == "sectionTestimonials" => {\n        heading,\n        testimonials[]-> {\n          _id, authorName, position, company, content, rating,\n          photo { ..., asset-> }\n        }\n      },\n      _type == "sectionStats" => {\n        heading,\n        items\n      },\n      _type == "sectionGallery" => {\n        heading,\n        images[] { ..., asset-> }\n      },\n      _type == "sectionBlogPreview" => {\n        heading,\n        count\n      },\n      _type == "sectionCta" => {\n        heading,\n        subheading,\n        primaryCta,\n        secondaryCta,\n        variant\n      },\n      _type == "sectionContact" => {\n        heading,\n        subheading\n      }\n    }\n  }\n': PageQueryResult
  }
}
